server:
  port: 8081

spring:
  application:
    name: admin-service
  profiles:
    active: ${QS_ENV}
  
  config:
    import: configserver:http://config-server.booking-app:8888

  cloud:
    config:
      uri: http://config-server.booking-app:8888
      name: admin-service
      username: ${QS_USERNAME}
      password: ${QS_PASSWORD}
      label: main
      fail-fast: true
